colors = [
    'alice blue', 'antique white', 'antique white 1', 'antique white 2', 'antique white 3',
    'antique white 4', 'aquamarine', 'aquamarine 1', 'aquamarine 2', 'aquamarine 3',
    'aquamarine 4', 'azure', 'azure 1', 'azure 2', 'azure 3', 'azure 4', 'beige', 'bisque',
    'bisque 1', 'bisque 2', 'bisque 3', 'bisque 4', 'black', 'blanched almond', 'blue',
    'blue 2', 'blue 3', 'blue 4', 'blue violet', 'brown', 'brown 1', 'brown 2', 'brown 3',
    'brown 4', 'burlywood', 'burlywood 1', 'burlywood 2', 'burlywood 3', 'burlywood 4',
    'cadet blue', 'cadet blue 1', 'cadet blue 2', 'cadet blue 3', 'cadet blue 4', 'chartreuse',
    'chartreuse 1', 'chartreuse 2', 'chartreuse 3', 'chartreuse 4', 'chocolate', 'chocolate 1',
    'chocolate 2', 'chocolate 3', 'chocolate 4', 'coral', 'coral 1', 'coral 2', 'coral 3',
    'coral 4', 'cornflower blue', 'cornsilk', 'cornsilk 1', 'cornsilk 2', 'cornsilk 3',
    'cornsilk 4', 'cyan', 'cyan 2', 'cyan 3', 'cyan 4', 'dark blue', 'dark cyan', 'dark goldenrod',
    'dark goldenrod 1', 'dark goldenrod 2', 'dark goldenrod 3', 'dark goldenrod 4', 'dark gray',
    'dark green', 'dark khaki', 'dark olive green', 'dark olive green 1', 'dark olive green 2',
    'dark olive green 3', 'dark olive green 4', 'dark orange', 'dark orange 1', 'dark orange 2',
    'dark orange 3', 'dark orange 4', 'dark orchid', 'dark orchid 1', 'dark orchid 2',
    'dark orchid 3', 'dark orchid 4', 'dark red', 'dark salmon', 'dark sea green',
    'dark sea green 1', 'dark sea green 2', 'dark sea green 3', 'dark sea green 4',
    'dark slate blue', 'dark slate gray', 'dark slate gray 1', 'dark slate gray 2',
    'dark slate gray 3', 'dark slate gray 4', 'dark turquoise', 'dark violet', 'deep pink',
    'deep pink 1', 'deep pink 2', 'deep pink 3', 'deep pink 4', 'deep sky blue',
    'deep sky blue 1', 'deep sky blue 2', 'deep sky blue 3', 'deep sky blue 4', 'dim gray',
    'dodger blue', 'dodger blue 1', 'dodger blue 2', 'dodger blue 3', 'dodger blue 4',
    'firebrick', 'firebrick 1', 'firebrick 2', 'firebrick 3', 'firebrick 4', 'floral white',
    'forest green', 'gainsboro', 'ghost white', 'gold', 'gold 2', 'gold 3', 'gold 4',
    'goldenrod', 'goldenrod 1', 'goldenrod 2', 'goldenrod 3', 'goldenrod 4', 'gray',
    'gray 0', 'gray 1', 'gray 10', 'gray 100', 'gray 11', 'gray 12', 'gray 13', 'gray 14',
    'gray 15', 'gray 16', 'gray 17', 'gray 18', 'gray 19', 'gray 2', 'gray 20', 'gray 21',
    'gray 22', 'gray 23', 'gray 24', 'gray 25', 'gray 26', 'gray 27', 'gray 28', 'gray 29',
    'gray 3', 'gray 30', 'gray 31', 'gray 32', 'gray 33', 'gray 34', 'gray 35', 'gray 36',
    'gray 37', 'gray 38', 'gray 39', 'gray 4', 'gray 40', 'gray 41', 'gray 42', 'gray 43',
    'gray 44', 'gray 45', 'gray 46', 'gray 47', 'gray 48', 'gray 49', 'gray 5', 'gray 50',
    'gray 51', 'gray 52', 'gray 53', 'gray 54', 'gray 55', 'gray 56', 'gray 57', 'gray 58',
    'gray 59', 'gray 6', 'gray 60', 'gray 61', 'gray 62', 'gray 63', 'gray 64', 'gray 65',
    'gray 66', 'gray 67', 'gray 68', 'gray 69', 'gray 7', 'gray 70', 'gray 71', 'gray 72',
    'gray 73', 'gray 74', 'gray 75', 'gray 76', 'gray 77', 'gray 78', 'gray 79', 'gray 8',
    'gray 80', 'gray 81', 'gray 82', 'gray 83', 'gray 84', 'gray 85', 'gray 86', 'gray 87',
    'gray 88', 'gray 89', 'gray 9', 'gray 90', 'gray 91', 'gray 92', 'gray 93', 'gray 94',
    'gray 95', 'gray 96', 'gray 97', 'gray 98', 'gray 99', 'green', 'green 2', 'green 3',
    'green 4', 'green yellow', 'honeydew', 'honeydew 1', 'honeydew 2', 'honeydew 3',
    'honeydew 4', 'hot pink', 'hot pink 1', 'hot pink 2', 'hot pink 3', 'hot pink 4',
    'indian red', 'indian red 1', 'indian red 2', 'indian red 3', 'indian red 4', 'ivory',
    'ivory 1', 'ivory 2', 'ivory 3', 'ivory 4', 'khaki', 'khaki 1', 'khaki 2', 'khaki 3',
    'khaki 4', 'lavender', 'lavender blush', 'lavender blush 1', 'lavender blush 2',
    'lavender blush 3', 'lavender blush 4', 'lawn green', 'lemon chiffon',
    'lemon chiffon 1', 'lemon chiffon 2', 'lemon chiffon 3', 'lemon chiffon 4', 'light blue',
    'light blue 1', 'light blue 2', 'light blue 3', 'light blue 4', 'light coral', 'light cyan',
    'light cyan 2', 'light cyan 3', 'light cyan 4', 'light goldenrod', 'light goldenrod 1',
    'light goldenrod 2', 'light goldenrod 3', 'light goldenrod 4', 'light goldenrod yellow',
    'light gray', 'light green', 'light pink', 'light pink 1', 'light pink 2', 'light pink 3',
    'light pink 4', 'light salmon', 'light salmon 1', 'light salmon 2', 'light salmon 3',
    'light salmon 4', 'light sea green', 'light sky blue', 'light sky blue 1',
    'light sky blue 2', 'light sky blue 3', 'light sky blue 4', 'light slate blue',
    'light slate gray', 'light steel blue', 'light steel blue 1', 'light steel blue 2',
    'light steel blue 3', 'light steel blue 4', 'light yellow', 'light yellow 1',
    'light yellow 2', 'light yellow 3', 'light yellow 4', 'lime green', 'linen', 'magenta',
    'magenta 2', 'magenta 3', 'magenta 4', 'maroon', 'maroon 1', 'maroon 2', 'maroon 3',
    'maroon 4', 'medium aquamarine', 'medium blue', 'medium orchid', 'medium orchid 1',
    'medium orchid 2', 'medium orchid 3', 'medium orchid 4', 'medium purple', 'medium purple 1',
    'medium purple 2', 'medium purple 3', 'medium purple 4', 'medium sea green',
    'medium slate blue', 'medium spring green', 'medium turquoise', 'medium violet red',
    'midnight blue', 'mint cream', 'misty rose', 'misty rose 1', 'misty rose 2',
    'misty rose 3', 'misty rose 4', 'moccasin', 'navajo white', 'navajo white 1',
    'navajo white 2', 'navajo white 3', 'navajo white 4', 'navy', 'navy blue', 'old lace',
    'olive drab', 'olive drab 1', 'olive drab 2', 'olive drab 3', 'olive drab 4', 'orange',
    'orange 2', 'orange 3', 'orange 4', 'orange red', 'orange red 1', 'orange red 2',
    'orange red 3', 'orange red 4', 'orchid', 'orchid 1', 'orchid 2', 'orchid 3', 'orchid 4',
    'pale goldenrod', 'pale green', 'pale green 1', 'pale green 2', 'pale green 3',
    'pale green 4', 'pale turquoise', 'pale turquoise 1', 'pale turquoise 2',
    'pale turquoise 3', 'pale turquoise 4', 'pale violet red', 'pale violet red 1',
    'pale violet red 2', 'pale violet red 3', 'pale violet red 4', 'papaya whip', 'peach puff',
    'peach puff 1', 'peach puff 2', 'peach puff 3', 'peach puff 4', 'peru', 'pink', 'pink 1',
    'pink 2', 'pink 3', 'pink 4', 'plum', 'plum 1', 'plum 2', 'plum 3', 'plum 4',
    'powder blue', 'purple', 'purple 1', 'purple 2', 'purple 3', 'purple 4', 'red', 'red 2',
    'red 3', 'red 4', 'rosy brown', 'rosy brown 1', 'rosy brown 2', 'rosy brown 3',
    'rosy brown 4', 'royal blue', 'royal blue 1', 'royal blue 2', 'royal blue 3',
    'royal blue 4', 'saddle brown', 'salmon', 'salmon 1', 'salmon 2', 'salmon 3',
    'salmon 4', 'sandy brown', 'sea green', 'sea green 1', 'sea green 2', 'sea green 3',
    'sea green 4', 'seashell', 'seashell 1', 'seashell 2', 'seashell 3', 'seashell 4',
    'sienna', 'sienna 1', 'sienna 2', 'sienna 3', 'sienna 4', 'sky blue', 'sky blue 1',
    'sky blue 2', 'sky blue 3', 'sky blue 4', 'slate blue', 'slate blue 1', 'slate blue 2',
    'slate blue 3', 'slate blue 4', 'slate gray', 'slate gray 1', 'slate gray 2',
    'slate gray 3', 'slate gray 4', 'snow', 'snow 1', 'snow 2', 'snow 3', 'snow 4',
    'spring green', 'spring green 1', 'spring green 2', 'spring green 3', 'spring green 4',
    'steel blue', 'steel blue 1', 'steel blue 2', 'steel blue 3', 'steel blue 4', 'tan',
    'tan 1', 'tan 2', 'tan 3', 'tan 4', 'thistle', 'thistle 1', 'thistle 2', 'thistle 3',
    'thistle 4', 'tomato', 'tomato 1', 'tomato 2', 'tomato 3', 'tomato 4', 'turquoise',
    'turquoise 1', 'turquoise 2', 'turquoise 3', 'turquoise 4', 'violet', 'violet red',
    'violet red 1', 'violet red 2', 'violet red 3', 'violet red 4', 'wheat', 'wheat 1',
    'wheat 2', 'wheat 3', 'wheat 4', 'white', 'white smoke', 'yellow', 'yellow 2',
    'yellow 3', 'yellow 4', 'yellow green'
]
